---
abstract: 'Compile and link C code for Perl modules'
author:
  - 'Ken Williams <kwilliams@cpan.org>, The Perl 5 Porters'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-CBuilder
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  File::Basename: 0
  File::Spec: 3.13
  File::Temp: 0
  IO::File: 0
  IPC::Cmd: 0
  Perl::OSType: 0
  Text::ParseWords: 0
version: 0.280205
